### ISSUE TITLE
特性需求 : 可以开发一种这样的新的计算机语言吗?

### ISSUE THREAD

**Issue by SilverLeaves** [rustlang-cn/articles#1]
可以开发一种这样的新的计算机语言吗?

看了知乎上的深入理解编译原理,有感. 故来询问.

## 像这样

```
事物 渣渣辉
事物 古添乐

渣渣辉 的 攻击力 = 5
古添乐 的 血量 = 10

动作 砍
{
    宾语 的 血量 = 宾语 的 血量 - 主语 的 攻击力
}

渣渣辉 砍 古添乐
// 结果 : 古添乐 的 血量 现在是5

```

等价于,js语句

```
let 渣渣辉={}
let 古添乐={}

渣渣辉.攻击力=5
古添乐.血量=10

function 砍(aim){
    aim.血量=aim.血量-this.攻击力
}

渣渣辉.砍 = 砍

渣渣辉.砍( 古添乐 )
// 结果 : 古添乐 的 血量 现在是5
```

## 运行示例
![default](https://user-images.githubusercontent.com/31165554/49651570-8cc50680-fa6a-11e8-9d65-41d04dd12307.png)

**Comment by SilverLeaves** [comment]
@krircc 我想实现这个语言,要学什么呢?要怎么开始呢?
我会一些c/c++, javascript.

**Comment by krircc** [comment]
这种话题还是找专家讨论的好
